"""added system_generations table

Revision ID: bfd4da2861c6
Revises: b1c2d3e4f5a6
Create Date: 2026-06-11 17:25:49.592093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd4da2861c6'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_generations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deployment_info_id', sa.Uuid(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('build_date', sa.DateTime(), nullable=False),
    sa.Column('nixos_version', sa.String(), nullable=False),
    sa.Column('kernel', sa.String(), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_info_id'], ['deployment_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('secrets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secrets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.drop_table('system_generations')
    # ### end Alembic commands ###
